### PR TITLE
Add ina4230 driver and fix max charge voltage

### LINKED ISSUE #90: Add Ina4230 support to RP2350

### PR DESCRIPTION
**Pull request by Skorpionm**
# What's new

- Drv: add drv ina4230
- Ina219 Drv: fix current_lsb
- Power Srv: fix max charge voltage 8,65v

# Verification 

- Uncomment the test_peref_srv thread, start Linux, and view the log output in the debug MCU.

# Contributor checklist

- [x] I have read the changes in this PR and understand what they do
- [x] I can explain the approach taken and why alternatives were not chosen
- [x] I have tested these changes myself (on hardware or in simulation)
- [x] I am able to respond to review comments on my own, not by forwarding them to an AI

> If you used AI tools to assist with this PR, that is fine — but the checklist above
> still applies to you personally.

### CODE REVIEW

File: lib/drivers/ina4230/ina4230.h [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+    SDA     VS          1001001 = 0x49
+    SDA     SDA         1001010 = 0x4A
+    SDA     SCL         1001011 = 0x4B
+    SCL     GND         1001100 = 0x4C
+    SCL     VS          1001101 = 0x4D
+    SCL     SDA         1001110 = 0x4E
+    SCL     SCL         1001111 = 0x4F
+*/
+typedef struct Ina4230 Ina4230;
+typedef void (*Ina4230CallbackInput)(void* context);
```
Comment (DrZlo13) [inline lib/drivers/ina4230/ina4230.h]: FuriCallback?

File: applications/applications.c [hunk 2]
```diff
@@ -79,13 +79,13 @@ const FlipperInternalApplication FLIPPER_SERVICES[] = {
...
     },
-    // {
-    //     .app = test_peref_srv,
-    //     .name = "TestPerefSrv",
-    //     .appid = "test_peref_srv",
-    //     .stack_size = 1024,
-    //     .flags = FlipperInternalApplicationFlagDefault,
-    // },
+    {
+        .app = test_peref_srv,
```
Comment (DrZlo13) [inline applications/applications.c]: forgot to comment out?

**Review by DrZlo13 — CHANGES_REQUESTED** [review]

File: applications/applications.c (hunk 2 above)
Comment (Skorpionm) [reply applications/applications.c]: fix

File: lib/drivers/ina4230/ina4230.h (hunk 1 above)
Comment (Skorpionm) [reply lib/drivers/ina4230/ina4230.h]: fix

**Review by DrZlo13 — APPROVED** [review]
